/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

    Author: Peter Vasil

  ==============================================================================
*/

#include "Application.h"

//==============================================================================
// This macro generates the main() routine that starts the app.
START_JUCE_APPLICATION(SynthAModelerApplication)
