// This DSP file has been generated by the Synth-A-Modeler compiler.
import("physicalmodeling.lib");

adjStiffness=hslider("stiffness", 2200.0, 500.0, 100.0, 4000.0);


bigBlock(m1p,m2p,m3p,dev1p,gp) = (m1,m2,m3,dev1,g,a1,a2) with {

	m1 = (0.0) : mass(0.01);
	m2 = (0.0) : mass(1e-2);
	m3 = (0.0) : mass(0.03);
	dev1 = (0.0);
	g = (0.0) : ground(0.0);

	a1 = m1*(1000.0)+l1*(100.0);
	a2 = l2*(1000.0)+l3*(-50.0)+l1*(0.01);
};

process = (bigBlock)~(_,_,_,_):(!,!,!,!,_,_,_);
